version: "3"

services:
  phoenix:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=db
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres